name: Release Validation
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - master
jobs:
  PR:
    name: Validation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
            versionSpec: '5.x'

      - name: Initialize GitVersion
        run: |
          if [ "${GITHUB_EVENT_NAME}" == "pull_request" ]; then
            if [ $(echo ${GITHUB_HEAD_REF} | grep -c '^release/') -eq 1 ]; then
              RELEASE_VERSION=$(echo ${GITHUB_HEAD_REF} | cut -d'/' -f2)
              echo -e "\nnext-version: ${RELEASE_VERSION}" >> ./GitVersion.yml
            fi
          fi

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Changelog check
        run: |
            grep --quiet --no-messages "^## \[$(echo ${{ steps.gitversion.outputs.majorMinorPatch }} | sed s/\\\./\\\\\./g)\]" ./CHANGELOG.md
            if [ $? -ne 0 ]; then
                echo "::error file=CHANGELOG.md::Don't forget to update the CHANGELOG with the change of this new release!"
                exit 1
            fi